debug: false                #Enables output to stdout
latitude: 0.0               #Latitude coordinate of the solar power plant
longitude: 0.0              #Longitude coordinate of the solar power plant
summary:
  telegram_url: "https://api.telegram.org/bot"
  bot_token: ""             #Secret Telegram Bot-Token
  chat_id: ""               #Chat ID
  send_statistics: false    #If disabled, no daily summary is send over Telegram
inverter:
  ip: ""                    #Inverter IP
  port: 1                   #Inverter Port
  device_id: ""             #Device ID of the inverter
logging:                    
  enabled: true             #Enable or disable logging
  file_name: "logs/log.log" #Choose logfile
persistence:
  url: "https://127.0.0.1:1234" #Set URL of your InfluxDB installation
  database_name:  ""             #Influx database name
  user: ""                      #Influx User
  password: ""                  #Influx Password